language: julia
julia:
  - 1.4.1
before_deploy:
  - "pwd"
  - "./get_solutions.sh"
deploy:
  - provider: pages:git
    skip_cleanup: true
    keep_history: true
    local_dir: "solutions"
    edge: true
