language: julia
julia:
  - 1.4.1
deploy:
  edge: true
  - provider: pages:git
    skip_cleanup: true
    keep_history: true
    local_dir: "solutions"
    before_deploy: "julia solutions.jl > solutions/solutions.md"
