language: julia
julia:
  - 1.4.1
before_deploy: "julia solutions.jl > solutions/solutions.md"
deploy:
  - provider: pages:git
    skip_cleanup: true
    keep_history: true
    local_dir: "solutions"
    edge: true
